apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    service: udagram-frontend
