apiVersion: v1
kind: Pod
metadata:
   name: backend-user
spec:
   containers:
     - name: backend-user
       image: omarzztelcocloud/udagram-api-user:v4
       envFrom:
         - configMapRef:
             name: env-secret
         - configMapRef:
             name: env-configmap
   restartPolicy: Never
